import { boolean, index, integer, jsonb, numeric, pgEnum, pgTable, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const membershipRole = pgEnum("membership_role", ["owner", "admin", "estimator", "accountant", "viewer"]);
export const resourceType = pgEnum("resource_type", ["work", "material", "machine", "equipment", "labor", "logistics", "service"]);

export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").notNull().default(false), name: text("name"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const organizations = pgTable("organizations", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), ownerId: uuid("owner_id").notNull().references(() => users.id), requisites: jsonb("requisites").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const memberships = pgTable("memberships", { organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), role: membershipRole("role").notNull() }, (table) => [primaryKey({ columns: [table.organizationId, table.userId] })]);
export const projects = pgTable("projects", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), region: text("region").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp("deleted_at", { withTimezone: true }) }, (table) => [index("projects_tenant_idx").on(table.organizationId)]);
export const threads = pgTable("threads", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), projectId: uuid("project_id").references(() => projects.id), title: text("title").notNull(), parentThreadId: uuid("parent_thread_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(), archivedAt: timestamp("archived_at", { withTimezone: true }) }, (table) => [index("threads_tenant_updated_idx").on(table.organizationId, table.updatedAt)]);
export const messages = pgTable("messages", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), threadId: uuid("thread_id").notNull().references(() => threads.id, { onDelete: "cascade" }), parentId: uuid("parent_id"), role: text("role").notNull(), content: jsonb("content").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("messages_thread_idx").on(table.organizationId, table.threadId, table.createdAt)]);
export const estimates = pgTable("estimates", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), projectId: uuid("project_id").notNull().references(() => projects.id), threadId: uuid("thread_id").notNull().references(() => threads.id), title: text("title").notNull(), activeRevision: integer("active_revision").notNull().default(1), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("estimates_tenant_project_idx").on(table.organizationId, table.projectId)]);
export const estimateRevisions = pgTable("estimate_revisions", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), estimateId: uuid("estimate_id").notNull().references(() => estimates.id, { onDelete: "cascade" }), revision: integer("revision").notNull(), payload: jsonb("payload").notNull(), total: numeric("total", { precision: 18, scale: 2 }).notNull(), createdBy: uuid("created_by").references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("estimate_revision_lookup_idx").on(table.organizationId, table.estimateId, table.revision)]);
export const estimateItems = pgTable("estimate_items", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), revisionId: uuid("revision_id").notNull().references(() => estimateRevisions.id, { onDelete: "cascade" }), sectionId: text("section_id").notNull(), name: text("name").notNull(), unit: text("unit").notNull(), quantity: numeric("quantity", { precision: 18, scale: 4 }).notNull(), unitPrice: numeric("unit_price", { precision: 18, scale: 2 }).notNull(), coefficient: numeric("coefficient", { precision: 12, scale: 4 }).notNull(), resourceType: resourceType("resource_type").notNull(), source: jsonb("source").notNull() }, (table) => [index("estimate_items_tenant_revision_idx").on(table.organizationId, table.revisionId)]);
export const agentRuns = pgTable("agent_runs", { id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), threadId: uuid("thread_id").notNull().references(() => threads.id), parentRunId: uuid("parent_run_id"), provider: text("provider").notNull(), model: text("model"), status: text("status").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), finishedAt: timestamp("finished_at", { withTimezone: true }), usage: jsonb("usage") }, (table) => [index("agent_runs_tenant_thread_idx").on(table.organizationId, table.threadId)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").primaryKey().defaultRandom(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), actorId: uuid("actor_id").references(() => users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), metadata: jsonb("metadata").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("audit_tenant_time_idx").on(table.organizationId, table.createdAt)]);
